import type { GraphConfidence, GraphEdgeKind, GraphEdgeV1, GraphNodeV1 } from "./graph-contracts.js";
import type { CommunitySummaryV1 } from "./analysis-store.js";

export interface GraphReportInputV1 {
  root: string;
  generation: string;
  generatedAt: string;
  godNodes: Array<{ node: GraphNodeV1; degree: number }>;
  communities: CommunitySummaryV1[];
  surprisingConnections: Array<{ from: GraphNodeV1; to: GraphNodeV1; kind: GraphEdgeKind; confidence: GraphConfidence; priority: "concept-code" | "cross-plane" }>;
  suggestedQuestions: string[];
  coverage: { totalCodeNodes: number; describedCodeNodes: number; coverageRatio: number };
  ambiguousEdges: Array<{ edge: GraphEdgeV1; from: GraphNodeV1 | undefined; to: GraphNodeV1 | undefined }>;
}

export function parseGraphReportGeneration(markdown: string): string | undefined {
  return markdown.match(/^# Graph Report\r?\n\r?\nGenerated [^\r\n]+ from graph generation `(g-[a-f0-9]{64})`\./u)?.[1];
}

export function renderGraphReportMarkdown(input: GraphReportInputV1): string {
  const lines: string[] = [];
  lines.push("# Graph Report");
  lines.push("");
  lines.push(
    `Generated ${input.generatedAt} from graph generation \`${input.generation}\`. This page is regenerated by \`update\` via \`graph --action report\`; do not edit it by hand.`,
  );
  lines.push("");

  lines.push("## God nodes");
  lines.push("");
  if (input.godNodes.length === 0) {
    lines.push("No god nodes identified yet.");
  } else {
    lines.push("| Node | Path | Degree |");
    lines.push("| --- | --- | --- |");
    for (const godNode of input.godNodes) {
      lines.push(`| ${godNode.node.name} | ${godNode.node.path} | ${String(godNode.degree)} |`);
    }
  }
  lines.push("");

  lines.push("## Communities");
  lines.push("");
  if (input.communities.length === 0) {
    lines.push("No communities identified yet.");
  } else {
    lines.push("| Community | Members | Top terms |");
    lines.push("| --- | --- | --- |");
    for (const community of input.communities) {
      lines.push(`| ${community.id} | ${String(community.memberCount)} | ${community.topTerms.join(", ") || "(none)"} |`);
    }
  }
  lines.push("");

  lines.push("## Surprising connections");
  lines.push("");
  if (input.surprisingConnections.length === 0) {
    lines.push("No cross-plane connections identified yet.");
  } else {
    lines.push("| From | To | Kind | Confidence | Priority |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const connection of input.surprisingConnections) {
      lines.push(
        `| ${connection.from.name} (${connection.from.path}) | ${connection.to.name} (${connection.to.path}) | ${connection.kind} | ${connection.confidence} | ${connection.priority} |`,
      );
    }
  }
  lines.push("");

  lines.push("## Suggested questions");
  lines.push("");
  if (input.suggestedQuestions.length === 0) {
    lines.push("No suggested questions yet.");
  } else {
    for (const question of input.suggestedQuestions) {
      lines.push(`- ${question}`);
    }
  }
  lines.push("");

  lines.push("## Coverage");
  lines.push("");
  lines.push(
    `${String(input.coverage.describedCodeNodes)} of ${String(input.coverage.totalCodeNodes)} code nodes are described by a wiki page or concept (${(input.coverage.coverageRatio * 100).toFixed(1)}%).`,
  );
  lines.push("");

  lines.push("## Ambiguous edges pending review");
  lines.push("");
  if (input.ambiguousEdges.length === 0) {
    lines.push("No ambiguous edges pending review.");
  } else {
    lines.push("| From | To | Kind |");
    lines.push("| --- | --- | --- |");
    for (const entry of input.ambiguousEdges) {
      lines.push(`| ${entry.from?.name ?? entry.edge.from} | ${entry.to?.name ?? entry.edge.to} | ${entry.edge.kind} |`);
    }
  }
  return `${lines.join("\n")}\n`;
}
